package:
  name: mfm
  version: 1.0.0
  top-level:
    - mfm
source:
  url: https://github.com/jmrohwer/mfm/archive/refs/tags/v1.0.0.zip
  sha256: 0df34abc86bb4d915de1238a660cc7028351ff04e813345021542ab5e13602bd
build:
  cflags: |
    -I$(WASM_LIBRARY_DIR)/include
    -Wno-return-type
    -DUNDERSCORE_G77
    -fvisibility=default
  cxxflags: |
    -fexceptions
    -fvisibility=default
  ldflags: |
    -L$(NUMPY_LIB)/core/lib/
    -L$(NUMPY_LIB)/random/lib/
    -fexceptions
  backend-flags: |
    build-dir=build
  script: |
    set -x
    git clone https://github.com/hoodmane/f2c.git --depth 1
    (cd f2c/src && cp makefile.u makefile && sed -i "s/gram.c:/gram.c1:/" makefile && make)
    export F2C_PATH=$(pwd)/f2c/src/f2c

    echo F2C_PATH: $F2C_PATH
    export NPY_BLAS_LIBS="-I$WASM_LIBRARY_DIR/include $WASM_LIBRARY_DIR/lib/libopenblas.so"
    export NPY_LAPACK_LIBS="-I$WASM_LIBRARY_DIR/include $WASM_LIBRARY_DIR/lib/libopenblas.so"

requirements:
  host:
    - numpy
  run:
    - numpy
  executable:
    - gfortran
about:
  summary:
    Project with mixed pure Python and Fortran sources
  license: BSD 3-Clause
extra:
  recipe-maintainers:
    - jmrohwer
